### ISSUE TITLE
AppSync JavaScript Resolvers: Error: Function metadata has exceeded the maximum allowed size.

### ISSUE THREAD

**Issue by MarcusCramer91** [aws/aws-appsync-community#301] opened 2023-06-27 15:09 UTC
I wanted to switch over from VTL resolvers to JavaScript resolvers. When trying to update the code in the AppSync GUI I get the error "Error: Function metadata has exceeded the maximum allowed size.". 

I assume this has to do something with the complexity of the function (like cyclomatic complexity?). When deleting more complex helper functions, the error disappears. When re-adding if-statements, loops, etc. the error re-appears.

It would be nice to

a) Understand what is going on here, and maybe get some documentation on this error. I cannot seem to find any, nor do I seem to find any specification regarding limitations here.
b) Increase that complexity limit, because the function I am using here really isn't super complex (cyclomatic complexity of 14, if that is used for the limit somehow). 

Cheers

**Comment by oyatrides** [comment] 2023-07-09 10:08
Hello, I have the same error, and I can't find anything on the documentation talking about this error.

**Comment by Oltier** [comment] 2023-07-13 16:11
I have a same error too...  The only documentation I found related to code size limits was this:

Maximum size of code | 32,000 characters per AWS AppSync function


However, I'm nowhere near this.
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-overview-js.html#additional-utilities

**Comment by mikebrantbison** [comment] 2023-08-11 15:34
Running into same issue on files that, once minified, are in ~9000 character range.  All files pass AppSync `evaluateCode` API test calls.

When trying to deploy `AWS::AppSync::FunctionConfiguration` via CDK, I get similar error of...

```Function metadata has exceeded the maximum allowed size. (Service: AmazonDeepdish; Status Code: 400; Error Code: BadRequestException```

What is meant by "metadata" here?  Is it just the size of the `code` string that is sent, or does something else contribute to the size of "metadata"?

**Comment by mikebrantbison** [comment] 2023-08-11 21:28
This did in fact turn out not to be a code size problem at all.

I looked at code commonly included/called by my two failing files and found the problem to be related related to calling the `toAwsPhone` function in the code below (only two of my files used this function).  Once I removed this code, everything deployed correctly.

I am including code here so as to hopefully give reproducable case of triggering this error.

File in which `toAwsPhone` if from

```
import { logError, stringSet, stringSetHas } from './util';

/**
 * Detect if passed string is in AppSync AWSPhone format
 * of /^+1[0-9]{10}$/
 *
 * @param {string} str
 * @returns boolean
 */
export const isAwsPhone = (str: string): boolean => {
	if (
		!str
		|| str.length !== 12
		|| str.charAt(0) !== '+'
		|| str.charAt(1) !== '1'
	) {
		return false;
	}
	return isNumeric(str.slice(2));
};

export const isNumeric = (str: string): boolean => str.split('').every(isNumberCharacter);

export const isNumberCharacter = (char: string): boolean => /* @__PURE__ */ stringSetHas(numberSet, char);

const numberSet = /* @__PURE__ */ stringSet('0123456789'.split(''));

/**
 * Extracts digits from passed possibly-formatted phone
 * number string, expecting 10 (or 11 with country code)
 * digits to be found.
 * Output meets AppSync AWSPhone format of /^+1[0-9]{10}$/
 *
 * @param {string} str
 * @returns string | void
 */
export const toAwsPhone = (str: string): string | void => {
	if (/* @__PURE__ */ isAwsPhone(str)) {
		return str;
	}

	const numbers = str.split('').filter(char => isNumberCharacter(char));

	if (numbers.length === 0) {
		return logError('no numbers found in passed phone string', 'BadRequest');
	}

	let phone = numbers.join('');

	if (phone.length === 10) {
		phone = '+1' + phone;
	} else if (phone.length === 11) {
		phone = '+' + phone;
	} else {
		return logError('incorrect string input length', 'BadRequest');
	}

	if (/* @__PURE__ */ isAwsPhone(phone)) {
		return phone;
	}

	return logError('unsupported phone number format', 'BadRequest');
};
```

utility file imported by above file (and in-lined in final build)

```
import { util } from '@aws-appsync/utils';

type Primitive = string | number | boolean | null | undefined;

export const cloneOmit = <T>(object: T, omitKeys: (keyof T)[]): T => {
	const clone = { ...object };
	omitKeys.forEach(key => {
		delete clone[key];
	});
	return clone;
};

export const logError = (msg: string, errorType?: string, data?: unknown, errorInfo?: unknown): void => {
	// this should only be true in AppSync resolver JS runtime
	/* c8 ignore start */
	if (util?.error) {
		util.error(msg, errorType, data, errorInfo);
	}
	/* c8 ignore stop */

	/* eslint-disable-next-line no-console */
	console.error(msg, { data, errorInfo, errorType });
};

export const logInfo = (msg: string, data?: unknown): void => {
	/* eslint-disable-next-line no-console */
	console.log(msg, data);
};

export type StringSet = {
	[key: string]: boolean;
};

export const stringSet = (strings?: string[]): StringSet => {
	strings = strings || [];

	const set: StringSet = {};

	strings.forEach(str => {
		set[str] = true;
	});

	return set;
};

export const stringSetAdd = (set: StringSet, str: string): void => {
	set[str] = true;
};

export const stringSetDelete = (set: StringSet, str: string): void => {
	delete set[str];
};

/* eslint-disable-next-line */ // keeps removing === true
export const stringSetHas = (set: StringSet, str: string): boolean => set[str] === true;

export const stringSetToArray = (set: StringSet): string[] => /* @__PURE__ */ Object.keys(set);

export const unique = <T extends Primitive>(array: T[]): T[] => {
	return array.filter((value, index, arr) => arr.indexOf(value) === index);
};

export const uniqueStrings = (strings: string[]): string[] => /* @__PURE__ */ stringSetToArray(stringSet(strings));
```

**Comment by mikebrantbison** [comment] 2023-08-16 16:24
As another follow-up.  I have been able to narrow down offending code the following.

This works...
```
var UserGrant = (props) => {
  props.roles = props.roles ?? [];
  return {
    ...props,
    ...createDynamoKeys5(props),
    Type: "UserGrant" /* UserGrant */
  };
};
```

This causes error...

```
var UserGrant = (props) => {
  const { roles = [] } = props;
  return {
    ...props,
    ...createDynamoKeys5(props),
    roles,
    Type: "UserGrant" /* UserGrant */
  };
};
```

The difference here seems to be in the default value assignment during destructuring operation. 

What is strange is I have the following in other areas of code, and I don't have this same issue...

```
  const { items = [], nextToken } = result;
  return { items, nextToken };
```

So to summarize for any people stumbling upon this...

- Pretty sure this is, at a minimum, a bug with AppSync or AppSync runtime that is giving bad error messaging
- At a minimum, AppSyncJS resolver documentation could use an update. While it claims support for destructuring, it does not seem to talk about whether variable defaulting (either in function params or when destructuring) is supported or in what circumstances it may be supported
- This could actually be a bug in AppSync JS runtime itself
- This message could represent a size issue, but clearly also is returned for other cases when size it not the issue at all.  Developers encountering this message, should first check size, but if you are not near 32K character limit, you will probably need to start trying to isolate portion of code where this is happening.  Looks specifically at destructuring / defaulting cases to see if they can be re-written without such usage.

**Comment by onlybakam** [comment] 2023-09-07 20:09
Hey @mikebrantbison , we've pushed out a couple of changes to address the issues. Can you let us know if you are still experiencing problems. 
Separately, we've also pushed out new DynamoDB utils that you can now use in your resolvers: https://aws.amazon.com/blogs/mobile/introducing-new-aws-appsync-module-and-functions-for-dynamodb-javascript-resolvers/

**Comment by onlybakam** [comment] 2023-12-11 21:49
Closing issue. Please let us know if you are still experiencing this problem

**Closed** 2023-12-11 21:48 UTC
