### ISSUE TITLE
RFC: Schema Information in datasource template

### ISSUE THREAD

**Issue by bboure** [aws/aws-appsync-community#3] opened 2019-02-28 09:53 UTC
In a data source request template, it would be great to be able to get some schema information about the executed query. Things like the path to the currently resolved field, the selection set, etc.

This would be useful, for example, to restrain, a database query to only the requested fields (instead of relying on appsync to filter out non-requested fields).
For that, a new object could be accessible in the `$context` object alongside with `arguments`, `source`, etc.

For example, we could do:

````graphql
## graphic schema
type Query {
	getUser(id: String!): User!
}

type User {
	id: Strng!
	email: String!
	firstName: String
	lastName: String
}
````

````graphql
## Query
query {
	getUser(id: "ca0b9299-3695-4107-82b8-77posdf538426a17") {
		id
		email
	}
}
````

````
## request template
{
	"version" : "2017-02-28",
	"operation" : "GetItem",
	"key" : {
		"id" : { "S" : "${context.arguments.id}" },
	},
	“select”: “SPECIFIC_ATTRIBUTES”,
	“attributesToGet”: $context.schemaInfo.selectionSet, ## pseudo-code
}
````

In fact, I expect something similar to the ´info´ field in the Apollo Project: https://www.apollographql.com/docs/graphql-tools/resolvers.html#Resolver-function-signature

**Comment by itrestian** [comment] 2019-03-03 17:48
Thank you for the feedback! We have heard this feature request in the past so I will +1 it internally on your behalf.

**Comment by tinnou** [comment] 2020-02-08 18:57
Duplicate of https://github.com/aws/aws-appsync-community/issues/49

**Comment by tinnou** [comment] 2020-02-08 19:07
Feature has been released https://github.com/aws/aws-appsync-community/commit/823d9c6f2b0acecaa9960945046bf922a29b56fe , please re-open an issue if you have a question.

**Closed by tinnou** 2020-02-08 19:07 UTC
Labels: enhancement
